---
languages: [fr_FR]
baseurl: "/"
sass:
  sass_dir: css
  style: compressed
permalink: /404.html
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
  syntax_highlighter: rouge
highlighter: rouge
gems:
- jekyll-paginate
- jekyll-seo-tag
- jemoji
exclude:
- vendor
plugins:
- jekyll-seo-tag
title: "Jeedom - pyenv4Jeedom"
description: "Page de documentation du plugin Jeedom 'pyenv4Jeedom'."
author: "Michel_F"
image: https://mrwaloo.github.io/pyenv4Jeedom/pyenv4Jeedom.png
social:
  name: Michel_F
  links:
    - https://mrwaloo.github.io/pyenv4Jeedom
---
